apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: local-peer
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: r0
  virtualRouters:
  - localASN: 64881
    exportPodCIDR: true
    serviceSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
    neighbors:
    - peerAddress: '10.110.0.254/32'
      peerASN: 64880
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: remote-peer
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/region: oracle
  virtualRouters:
  - localASN: 64882
    exportPodCIDR: true
    serviceSelector:
       matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
    neighbors:
    - peerAddress: '10.99.0.42/32'
      peerASN: 64770
      eBGPMultihopTTL: 3
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120

